export const USER_LOGIN_INFO_REQUEST = 'USER_LOGIN_INFO_REQUEST'
export const USER_LOGIN_INFO_SUCCESS = 'USER_LOGIN_INFO_SUCCESS'
export const USER_LOGIN_INFO_FAIL = 'USER_LOGIN_INFO_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'