export const UPDATE_DISH_REQUEST = 'UPDATE_DISH_REQUEST'
export const UPDATE_DISH_SUCCESS = 'UPDATE_DISH_SUCCESS'
export const UPDATE_DISH_FAIL = 'UPDATE_DISH_FAIL'
export const UPDATE_DISH_RESET = 'UPDATE_DISH_RESET'