export const DISH_DELETE_REQUEST = 'DISH_DELETE_REQUEST'
export const DISH_DELETE_SUCCESS = 'DISH_DELETE_SUCCESS'
export const DISH_DELETE_FAIL = 'DISH_DELETE_FAIL'
export const DISH_DELETE_RESET = 'DISH_DELETE_RESET'