export const RESTAURANT_CREATE_REQUEST = "RESTAURANT_CREATE_REQUEST";
export const RESTAURANT_CREATE_SUCCESS = "RESTAURANT_CREATE_SUCCESS";
export const RESTAURANT_CREATE_FAIL = "RESTAURANT_CREATE_FAIL";
export const RESTAURANT_CREATE_RESET = "RESTAURANT_CREATE_RESET";



