export const RESTAURANT_LOCATION_REQUEST = "RESTAURANT_LOCATION_REQUEST";
export const RESTAURANT_LOCATION_SUCCESS = "RESTAURANT_LOCATION_SUCCESS";
export const RESTAURANT_LOCATION_FAIL = "RESTAURANT_LOCATION_FAIL";
