export const RESTAURANT_UPDATE_REQUEST = 'RESTAURANT_UPDATE_REQUEST'
export const RESTAURANT_UPDATE_SUCCESS = 'RESTAURANT_UPDATE_SUCCESS'
export const RESTAURANT_UPDATE_FAIL = 'RESTAURANT_UPDATE_FAIL'
export const RESTAURANT_UPDATE_RESET = 'RESTAURANT_UPDATE_RESET'