export const RESTAURANT_DELETE_REQUEST = 'RESTAURANT_DELETE_REQUEST'
export const RESTAURANT_DELETE_SUCCESS = 'RESTAURANT_DELETE_SUCCESS'
export const RESTAURANT_DELETE_FAIL = 'RESTAURANT_DELETE_FAIL'
export const RESTAURANT_DELETE_RESET = 'RESTAURANT_DELETE_RESET'