export const DISH_CREATE_REQUEST = 'DISH_CREATE_REQUEST'
export const DISH_CREATE_SUCCESS = 'DISH_CREATE_SUCCESS'
export const DISH_CREATE_FAIL = 'DISH_CREATE_FAIL'
export const DISH_CREATE_RESET = 'DISH_CREATE_RESET'